# Generated by Django 5.0.4 on 2024-05-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_remove_category_featured_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
